services:
  db:
    image: postgres:15
    container_name: effortlog-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - effortlog-network

  backend:
    build:
      context: ./effort_log_api
    container_name: effortlog-api
    depends_on:
      - db
    ports:
      - "${PORT:-3366}:3366"
    env_file:
      - ./effort_log_api/.env
    restart: on-failure
    networks:
      - effortlog-network

  frontend:
    build:
      context: ./effort_log
    container_name: effortlog-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - ./effort_log/.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3366
    networks:
      - effortlog-network

volumes:
  postgres_data:


networks:
  effortlog-network:
    driver: bridge
